Fix SECURITY_STRINGFORMAT compile error in ums
:Release Notes:
Addressed SECURITY_STRINGFORMAT compilation error in ums
to remove temporary workaround in bb file.

:Detailed Notes:
Addressed SECURITY_STRINGFORMAT compilation error in ums
to remove temporary fix which was causing below error.
git/src/logger/Logger_macro.h:186:38: error: format not a
string literal and no format arguments [-Werror=format-security]
char message[MAX_FT_SIZE]; snprintf(message, MAX_FT_SIZE, format, args...);
                              ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

:Testing Performed:
[QWTC-475] [HTML5] Verify URL Playback

:QA Notes:
NA

:Issues Addressed:
[WRP-8741] Fix SECURITY_STRINGFORMAT compile error in ums

Signed-off-by: veeresh kadasani <veeresh.kadasani@lge.com>
Change-Id: I96336f2eb92d5b7bf334c8aa81c316a86fbbcc3a