Fix build with boost-1.84.0
:Release Notes:
Upgraded in:
https://git.openembedded.org/openembedded-core/commit/?h=scarthgap&id=4a7f5ec28712645d968e6dce84a7bd8bae8b4eb2
See:
https://www.boost.org/users/history/version_1_84_0.html

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/792313

FAILED: src/resource_manager/CMakeFiles/resource_mgr.dir/AcquireQueue.cpp.o
ccache TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot -DUMS_INTERNAL_API_VERSION=2 -Dresource_mgr_EXPORTS -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/git/include/public -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/git/src/resource_manager -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/git/src/logger -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/git/src/timer -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/git/src/config_file_reader -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/git/src/utils -mcpu=cortex-a72+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/git=/usr/src/debug/umediaserver/1.0.0-gav.43  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/git=/usr/src/debug/umediaserver/1.0.0-gav.43  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/build=/usr/src/debug/umediaserver/1.0.0-gav.43  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/build=/usr/src/debug/umediaserver/1.0.0-gav.43  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot-native=  -fvisibility-inlines-hidden -std=c++11 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/git/include/public -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/git/src/resource_manager -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/include -pthread -pthread -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/include/gstreamer-1.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/include/orc-0.4 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/include/gstreamer-1.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/include -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysroot/usr/include -DLTTNG_PMTRACE -DTRACEPOINT_DEFINE -DTRACEPOINT_PROBE_DYNAMIC_LINKAGE -DENABLE_PMTRACE -DPERFLOG_USE_PMLOG -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/recipe-sysrootinclude -DNDEBUG -fPIC -MD -MT src/resource_manager/CMakeFiles/resource_mgr.dir/AcquireQueue.cpp.o -MF src/resource_manager/CMakeFiles/resource_mgr.dir/AcquireQueue.cpp.o.d -o src/resource_manager/CMakeFiles/resource_mgr.dir/AcquireQueue.cpp.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/umediaserver/1.0.0-gav.43/git/src/resource_manager/AcquireQueue.cpp
../git/src/resource_manager/AcquireQueue.cpp: In member function 'void uMediaServer::AcquireQueue::policyActionResult(const std::string&, bool)':
../git/src/resource_manager/AcquireQueue.cpp:55:42: error: no matching function for call to 'find(std::__cxx11::list<std::__cxx11::basic_string<char> >::iterator, std::__cxx11::list<std::__cxx11::basic_string<char> >::iterator, const std::string&)'
   55 |                                 std::find(candidates.begin(), candidates.end(), candidate_id) != candidates.end()) {
      |                                 ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../recipe-sysroot/usr/include/c++/13.2.0/bits/locale_facets.h:48,
                 from ../recipe-sysroot/usr/include/c++/13.2.0/bits/basic_ios.h:37,
                 from ../recipe-sysroot/usr/include/c++/13.2.0/ios:46,
                 from ../recipe-sysroot/usr/include/c++/13.2.0/istream:40,
                 from ../recipe-sysroot/usr/include/c++/13.2.0/sstream:40,
                 from ../git/src/resource_manager/ResourceManager.h:21,
                 from ../git/src/resource_manager/AcquireQueue.h:23,
                 from ../git/src/resource_manager/AcquireQueue.cpp:18:
../recipe-sysroot/usr/include/c++/13.2.0/bits/streambuf_iterator.h:435:5: note: candidate: 'template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT, std::char_traits<_CharT> > >::__type std::find(istreambuf_iterator<_CharT, char_traits<_CharT> >, istreambuf_iterator<_CharT, char_traits<_CharT> >, const _CharT2&)'
  435 |     find(istreambuf_iterator<_CharT> __first,
      |     ^~~~
../recipe-sysroot/usr/include/c++/13.2.0/bits/streambuf_iterator.h:435:5: note:   template argument deduction/substitution failed:
../git/src/resource_manager/AcquireQueue.cpp:55:42: note:   'std::_List_iterator<std::__cxx11::basic_string<char> >' is not derived from 'std::istreambuf_iterator<_CharT, std::char_traits<_CharT> >'
   55 |                                 std::find(candidates.begin(), candidates.end(), candidate_id) != candidates.end()) {
      |                                 ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

with boost-1.83.0 algorithm was included only implicitly through:
/usr/include/boost/lexical_cast.hpp
/usr/include/boost/range/iterator_range_core.hpp
/usr/include/boost/range/functions.hpp
/usr/include/boost/range/size.hpp
/usr/include/boost/range/size_type.hpp
/usr/include/boost/range/concepts.hpp
/usr/include/boost/iterator/iterator_concepts.hpp
/usr/include/c++/13.2.0/algorithm

but lexical_cast.hpp doesn't include range anymore since:
https://github.com/boostorg/lexical_cast/commit/1ca93a8e275c88efd83b3d622547faef697e0f42

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-504] Create GPVB with Yocto 5.0 Scarthgap

Change-Id: Idc8080e4590b1888b6736b784b490d3ec06bb235